### ISSUE TITLE
Open wiki

### ISSUE THREAD

**Issue by aggsol** [MasterQ32/VersaTile#11]
How about opening the wiki so we can collect snippets and How-Tos like how to build?

**Comment by ikskuh** [comment]
Opened a wiki, can you edit it? I'll take a closer look onto your pull request tomorrow

**Comment by aggsol** [comment]
No I can't. You need to make it public of form a team I guess.

**Comment by ikskuh** [comment]
It should be editable now... At least. i hope so^^
Have to learn all the GitHub stuff besides repo hosting

**Comment by aggsol** [comment]
Works! :+1:
