### ISSUE TITLE
Save dialog does not work as expected

### ISSUE THREAD

**Issue by aggsol** [MasterQ32/VersaTile#12]
Current master version.
Repro:
* Create new model
* Click Save...
* Select save location
* Enter filename `testname`
* Click Save...
* Click Open
* Locate save location
--> No file to open.

I assume it's because of the missing file extension.

1. Adding extension if missing
2. Allow opening any file with any extension?

**Comment by ikskuh** [comment]
Have chosen 1., resolved with 65b64ce74bf5f533cf6b95c9537ee2ff172e39fc .
