### ISSUE TITLE
Nomenclature: Sprite vs. Tile

### ISSUE THREAD

**Issue by aggsol** [MasterQ32/VersaTile#18]
Just for my under standing:

When it's 2D and in the right window then it's a sprite.
When it's 3D as part of a model then it's a tile.

Or the other way round?

**Comment by ikskuh** [comment]
That's actually a good question, I'll think about it!

**Comment by ikskuh** [comment]
Resolved with Wiki-Entry: [Nomenclature](https://github.com/MasterQ32/VersaTile/wiki/Nomenclature)
