### ISSUE TITLE
Another example texture

### ISSUE THREAD

**Issue by aggsol** [MasterQ32/VersaTile#29]
The example texture draws a connection to [Crocotile3D](http://www.crocotile3d.com/) which is there (obviously) but having a unique default texture would help the project to distinguish itself like  [Sprytile](https://github.com/ChemiKhazi/Sprytile) does. Maybe we find something with a free license (like CC0 or similar) which can be used for a good example model.

**Comment by ikskuh** [comment]
Yeah, i'm thinking about this from day one...

The problem is that you can't just grab a usual tile set as those mostly contain a certain perspective already. Maybe i'll draw some textures myself, but i'm not good enough right now for this.

**Comment by ikskuh** [comment]
I found this texture: https://opengameart.org/content/2d-castle-platformer-starter-assets
![](https://opengameart.org/sites/default/files/sample1_2.png)

It seems quite good to build some castle/dungeon-styled models with it, although it's missing a lot of components

**Comment by ikskuh** [comment]
It's a good base at least:
![](https://puu.sh/wXGND/2a17f8ef45.png)

**Comment by ikskuh** [comment]
I also tried a tileset from [kenney.nl](http://kenney.nl/assets/roguelike-caves-dungeons):

![](https://puu.sh/wYx0J/be1c218ae0.png)

This looks also quite good, but: We need a better texture importer

**Comment by ikskuh** [comment]
I think i'll go with the kenney.nl tileset as a default tileset. It offers much flexibility and suits the editor style
