### ISSUE TITLE
Fix export

### ISSUE THREAD

**Issue by ikskuh** [MasterQ32/VersaTile#30]
The export right now is unbearably broken, although Assimp is used.

Proposal:
Remove Assimp, write own OBJ exporter with correct texture export

**Comment by aggsol** [comment]
Collada and FBX should be options too. Is Assimp broken or are we using it just wrong?

**Comment by ikskuh** [comment]
I don't know. I think it actually has some problems with the export as the **3ds** models are missing the second face (it seems that no triangulation happens), obj doesn't export a texture file (but sets a texture name), and the COLLADA export writes the texture file into the wrong folder (and references it wrong, so if i move it, it won't be loaded anyways)

**Comment by ikskuh** [comment]
I have made a small fix in 40e5f7747baa139ee8fd93c9d0a41eb58ff40189 which fixes the export for obj by writing the texture out myself. Should do the stuff for the most parts.
