### ISSUE TITLE
Improve tileset options

### ISSUE THREAD

**Issue by ikskuh** [MasterQ32/VersaTile#31]
When creating a new model, add a preprocessing step for the tilesets to remove any margins and tile paddings from the sprite sheet, so more sprite sheets can be used.

Maybe also add an option for "previewing" the imported tile set with a grid on import.

**Comment by aggsol** [comment]
Or use the ideas from #17 On the first imports create a tile set description file that stores margins, tile size etc. I feel #31 and #17 are in the end very similar and might use the same solution.

**Comment by ikskuh** [comment]
Yeah, the idea is quite similar and will later be replaced with the more complex version of #17 . But for now, i just want a solution that is usable for the 1.0 version and don't bring in the complex features already.

Also, a reminder for myself: When reimporting the texture, it requires a dialog that also brings up the tilesheet options.

**Comment by ikskuh** [comment]
I improved the current "new file" dialog as well (now uses the same dialog as "update texture"):
![](https://puu.sh/wYEQZ/13b437bec4.png)

**Comment by ikskuh** [comment]
Resolved with f6bc8cadf3ad5412b39704d984e82a67a1dfe37d
