### ISSUE TITLE
Snapping to grid (from topview)

### ISSUE THREAD

**Issue by 3RUN** [MasterQ32/VersaTile#4]
It seems that there is an offset from the mouse position, when I try to place a tile from top view. I moved camera/grid upwards, and there was like one tile offset, it might be a bug?

**Comment by ikskuh** [comment]
Yeah, this is a known bug, based on some integer rounding. I should fix this for the next release.

**Comment by ikskuh** [comment]
Should be fixed with b4589d024894f69b3e02e1933944950d35946696
