### ISSUE TITLE
Cannot build because of hardcoded paths in project

### ISSUE THREAD

**Issue by aggsol** [MasterQ32/VersaTile#6]
When I open the project in QtCreator it can't compile because of hard coded paths:
```
Cannot read /home/felix/projects/gl3w/gl3w.pri: No such file or directory
```
I am using 
* Ubuntu 16.04.2 LTS 64-bit
* Qt Creator 3.5.1
* libassimp-dev/xenial 3.2~dfsg-3 amd64

**Comment by kaadmy** [comment]
A quick bandaid right now is to clone `https://github.com/MasterQ32/gl3w`, compile it, and use the .pri file in that directory.

**Comment by aggsol** [comment]
This is kinda hacky. I look for another way.

**Comment by ikskuh** [comment]
The pri file is actually the way to build right now. Maybe i can add the gl3w fork as a submodule...

**Comment by aggsol** [comment]
It even worse Qt and QtCreator from the repositories do not know `QOpenGLWidget`. What are the exact version requirements to build?

**Comment by ikskuh** [comment]
I have _Qt Creator 4.3.1 based on Qt 5.9.1_, but the QOpenGLWidget should be available at least since Qt5 and i don't use that much of special Qt features, so it should run fine with Qt 5.3 or even previous versions

**Comment by aggsol** [comment]
I works now with the latest version.
