### ISSUE TITLE
OpenGL problems

### ISSUE THREAD

**Issue by kaadmy** [MasterQ32/VersaTile#7]
I have OpenGL 3.3 on Arch Linux, and I get this log when running it:

```
Change mesh, set mesh as clean.
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
Unrecognized OpenGL version
Unrecognized OpenGL version
```

**Comment by ikskuh** [comment]
Hm, this is weird. Can you post a log of `glxinfo  | grep -i opengl`? It should be using OpenGL 3.3...

I'm using Arch Linux as well with mesa as the graphics driver

**Comment by kaadmy** [comment]
```
OpenGL vendor string: NVIDIA Corporation
OpenGL renderer string: GeForce 9300M GS/PCIe/SSE2
OpenGL core profile version string: 3.3.0 NVIDIA 340.102
OpenGL core profile shading language version string: 3.30 NVIDIA via Cg compiler
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 3.3.0 NVIDIA 340.102
OpenGL shading language version string: 3.30 NVIDIA via Cg compiler
OpenGL context flags: (none)
OpenGL profile mask: (none)
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 2.0 NVIDIA 340.102 340.102
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 1.00
OpenGL ES profile extensions:
```

I think that should be perfectly valid, not sure what's happening.

**Comment by ikskuh** [comment]
I'll take a look...
Maybe you can disable the multisampling in `modeleditorview.cpp`, line 54:

```cpp
{
	QSurfaceFormat fmt;
	fmt.setVersion(3, 3);
	// fmt.setSamples(8); <-
	this->setFormat(fmt);
	this->setMouseTracking(true);
	connect(
	    this, &ModelEditorView::meshIsAboutToChange,
	    this, &ModelEditorView::addUndoStep);
}
```

**Comment by kaadmy** [comment]
Huh. I just ran versa-tile through a terminal and it worked perfectly, running it through QtCreator still yields  the same error.
Not related but a bit annoying, I also get spammed with tons of `"Buffer detailed info: Buffer object 1 (bound to GL_VERTEX_ATTRIB_ARRAY_BUFFER_BINDING_ARB (0), GL_VERTEX_ATTRIB_ARRAY_BUFFER_BINDING_ARB (1), and GL_ARRAY_BUFFER_ARB, usage hint is GL_STATIC_DRAW) will use VIDEO memory as the source for buffer object operations."
` while running it.

**Comment by ikskuh** [comment]
Do you have a NVIDIA Optimus system? Maybe i should add an option for OpenGL logging to the editor

**Comment by kaadmy** [comment]
I think I have a shared IGPU/DGPU but I'm not positive, I just force the nVidia GPU always on anyway via Xorg.conf

**Comment by ikskuh** [comment]
I really have no idea what to do with this...
