### ISSUE TITLE
Cannot select tile

### ISSUE THREAD

**Issue by aggsol** [MasterQ32/VersaTile#8]
I current build from master

* Ubuntu 16.04.2 LTS 64-bit
* Qt Creator 4.3.1
* Qt 5.9.1 64bit GCC

The tile in the red rectangle cannot be selected only larger groups around it.

![cannot_select](https://user-images.githubusercontent.com/719279/28427418-6e6b79e4-6d76-11e7-933e-c216e16dd2a6.png)

**Comment by ikskuh** [comment]
Hm, i can select it by just clicking the tile:
![](https://puu.sh/wOz7J/688509049f.png)

**Comment by ikskuh** [comment]
Sorry, misclicked that one

**Comment by aggsol** [comment]
Sorry, I forgot a step. I zoomed the tile set 2x as you can see it is larger than in your screenshot.

**Comment by ikskuh** [comment]
Fixed in 8da096a67a994bf09c9830a7cff4760f99b39199
